[build]
ignore-vcs = true
artifacts = [
    "*.so",
    "*.dll",
]

[build.targets.wheel.hooks.custom]
path = "../src/hatch_cython/devel.py"
dependencies = [
  "Cython",
  "setuptools",
  "numpy"
]

[build.targets.wheel.hooks.custom.options]
include_numpy = true
compile_args = [
  { platforms = "posix", arg = "" }
]


[[envs.all.matrix]]
python = ["3.10", "3.11"]

[envs.lint]
detached = true
dependencies = [
  "black>=23.1.0",
  "mypy>=1.0.0",
  "ruff>=0.0.243",
]


[envs.lint.scripts]
typing = "mypy --install-types --non-interactive {args:src/funcclasses tests}"
style = [
  "ruff {args:.}",
  "black --check --diff {args:.}",
]
fmt = [
  "black {args:.}",
  "ruff --fix {args:.}",
  "style",
]
all = [
  "style",
  "typing",
]

[envs.default]
python = "3.11"
dependencies = [
  "coverage",
  "pytest",
  "beartype",
  "numpy",
]

[envs.default.scripts]
install = "pip install dist/example-0.0.1-*.whl --force-reinstall"
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = [
  "- coverage combine",
  "coverage report",
]
cov = [
  "install",
  "test-cov",
  "cov-report",
]
