name: test

on:
  push:
    branches: [main, v*]
  pull_request:
    branches: [main, v*]

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    name: Python ${{ matrix.python-version }} on ${{ startsWith(matrix.os[0], 'macos-') && 'macOS' || startsWith(matrix.os[0], 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [[ubuntu-latest, x64], [windows-latest, x64], [macos-latest, x64]]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Install
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew install libomp llvm &&
          brew link llvm &&
          echo $(brew info llvm) &&
          echo $(arch)

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          architecture: ${{matrix.os[1]}}
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: pip install --upgrade hatch

      - name: Run tests
        run: hatch run cov

      - name: Test Compile
        shell: bash
        run:   |
              if [ "$RUNNER_OS" == "Windows" ]; then
                echo "using native C++"
              else
                echo "using g++"
                export CC=g++
                export CXX=g++
              fi
              cd example
              echo $RUNNER_OS
              hatch build
              hatch run cov
